# prefix 1 - 1 hour
60:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>I<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix i"
# prefix 2 - 8 hours
480:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>II<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix ii"
# prefix 3 - 20 hours
1200:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>III<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix iii"
# prefix 4 - 45 hours
2700:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>IV<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix iv"
# prefix 5 - 90 hours
5400:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>V<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix v"
# prefix 6 - 170 hours
10200:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>VI<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix vi"
# prefix 7 - 320 hours
19200:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>VII<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix vii"
# prefix 8 - 580 hours
34800:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>VIII<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix viii"
# prefix 9 - 1090 hours
65400:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <#949bd1>IX<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix ix"
# prefix X - 2000 hours
120000:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <DARK_RED>X<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix x"
# prefix Y - 5000 hours
300000:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <DARK_RED>Y<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix y"
# prefix Z - 15000 hours
900000:
  broadcasts:
    - "<white>• <#949bd1><username> <#656b96>has earned prefix <DARK_RED>Z<#656b96>!"
  console-commands:
    - "lp user <username> parent settrack prefix z"