name: FeatherPrefix
version: '${project.version}'
main: dev.zerek.featherprefix.FeatherPrefix
api-version: 1.19
depend: [ LuckPerms ]
authors: [ Zerek ]
description: Display roman numeral prefixes based on time played.
commands:
  prefix:
    description: View prefix chart and check current hours.